#pragma once

enum Kind {
	KIND_EOF,
	
	KIND_LITERAL_BOOL,
	KIND_LITERAL_CHAR,
	KIND_LITERAL_INT,
	KIND_LITERAL_FLOAT,
	KIND_LITERAL_STRING,
	KIND_LITERAL_IDENTIFIER,
	
	KIND_OPERATOR_ADD,
	KIND_OPERATOR_SUB,
	KIND_OPERATOR_MUL,
	KIND_OPERATOR_DIV,
	KIND_OPERATOR_MOD,
	KIND_OPERATOR_POW,
	
	KIND_OPERATOR_ASN,
	
	KIND_OPERATOR_OR,
	KIND_OPERATOR_NOT,
	KIND_OPERATOR_AND,
	
	KIND_OPERATOR_LT,
	KIND_OPERATOR_GT,
	KIND_OPERATOR_EQ,
	KIND_OPERATOR_NEQ,
	KIND_OPERATOR_LTE,
	KIND_OPERATOR_GTE,
	
	KIND_OPERATOR_BIT_OR,
	KIND_OPERATOR_BIT_NOT,
	KIND_OPERATOR_BIT_AND,
	KIND_OPERATOR_BIT_XOR,
	KIND_OPERATOR_BIT_SHR,
	KIND_OPERATOR_BIT_SHL,
	
	KIND_DELIMITER_LPN,
	KIND_DELIMITER_RPN,
	KIND_DELIMITER_LBK,
	KIND_DELIMITER_RBK,
	KIND_DELIMITER_LBK,
	KIND_DELIMITER_RBK,
	
	KIND_DELIMITER_NL,
	
	KIND_DELIMITER_PRD,
	KIND_DELIMITER_CMA,
	KIND_DELIMITER_CLN,
	KIND_DELIMITER_SMI,
	
	KIND_KEYWORD_I8, KIND_KEYWORD_U8,
	KIND_KEYWORD_I16, KIND_KEYWORD_U16,
	KIND_KEYWORD_I32, KIND_KEYWORD_U32,
	KIND_KEYWORD_I64, KIND_KEYWORD_U64,
	KIND_KEYWORD_F32, KIND_KEYWORD_F64,
	
	KIND_KEYWORD_ENUM, KIND_KEYWORD_STRUCT,
	KIND_KEYWORD_OBJECT,
	
	KIND_KEYWORD_FUN, KIND_KEYWORD_MODULE,
	KIND_KEYWORD_NAMESPACE,
	
	KIND_KEYWORD_FOR, KIND_KEYWORD_WHILE,
	KIND_KEYWORD_DO,
	
	KIND_KEYWORD_IF, KIND_KEYWORD_ELSE,
	KIND_KEYWORD_MATCH, KIND_KEYWORD_CASE,
	KIND_KEYWORD_DEFAULT,
	
	KIND_KEYWORD_RETURN, KIND_KEYWORD_CONTINUE,
	KIND_KEYWORD_BREAK,
	
	KIND_KEYWORD_IMPORT, KIND_KEYWORD_FROM,
	KIND_KEYWORD_FROM, KIND_KEYWORD_USE,
	KIND_KEYWORD_INCLUDE
};
